# Generated by Django 5.2.4 on 2025-08-01 13:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbs in grams', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats in grams', max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, help_text='Fiber in grams', max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, help_text='Sugar in grams', max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, help_text='Sodium in mg', max_digits=6)),
                ('serving_size', models.CharField(default='100g', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/')),
                ('detected_foods', models.JSONField(default=list, help_text='List of detected food items')),
                ('confidence_scores', models.JSONField(default=list, help_text='Confidence scores for detections')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very active (hard exercise/sports 6-7 days a week)'), ('extremely_active', 'Extremely active (very hard exercise/sports & physical job)')], default='sedentary', max_length=20)),
                ('target_calories', models.PositiveIntegerField(default=2000)),
                ('target_protein', models.PositiveIntegerField(default=150, help_text='Target protein in grams')),
                ('target_carbs', models.PositiveIntegerField(default=250, help_text='Target carbs in grams')),
                ('target_fats', models.PositiveIntegerField(default=65, help_text='Target fats in grams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('custom_food_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantity in servings', max_digits=5)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fooditem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'meal_type', 'food_item', 'custom_food_name')},
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_calories', models.PositiveIntegerField()),
                ('target_protein', models.PositiveIntegerField()),
                ('target_carbs', models.PositiveIntegerField()),
                ('target_fats', models.PositiveIntegerField()),
                ('actual_calories', models.PositiveIntegerField(default=0)),
                ('actual_protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
